services:
  ac-database:
    environment:
      TZ: ${TZ}

  ac-worldserver:
    environment:
      TZ: ${TZ}
    volumes:
      - ./modules:/azerothcore/modules
      - ../wotlk/etc:/azerothcore/env/dist/etc